### ISSUE TITLE
Error | Numeric Pattern 107

### ISSUE THREAD

**Issue by ChlorinePentoxide** [openAOD/C-PatternHouse#901]
Error in 'main' branch
Compiler: GCC
```
/usr/bin/ld: /tmp/ccmTsm0V.o: in function `main': 00:03
numericpattern107.c:(.text+0x6e): undefined reference to `pow' 00:03
/usr/bin/ld: numericpattern107.c:(.text+0xad): undefined reference to `pow' 00:03
collect2: error: ld returned 1 exit status
```
@aryashah2k Please look into this issue. The original committer @Srishti-Ahuja cannot be assigned on this issue as they are not a member in this organization.

**Comment by aryashah2k** [comment]
@Srishti-Ahuja, I request you to please join the organization. Thanks for bringing this to my notice @ChlorinePentoxide . I will relay the same on the SWOC channel as well

**Comment by aryashah2k** [comment]
> Error in 'main' branch Compiler: GCC
> 
> ```
> /usr/bin/ld: /tmp/ccmTsm0V.o: in function `main': 00:03
> numericpattern107.c:(.text+0x6e): undefined reference to `pow' 00:03
> /usr/bin/ld: numericpattern107.c:(.text+0xad): undefined reference to `pow' 00:03
> collect2: error: ld returned 1 exit status
> ```
> 
> @aryashah2k Please look into this issue. The original committer @Srishti-Ahuja cannot be assigned on this issue as they are not a member in this organization.

I think she hasnt included the #include<math.h> which is required for the pow function, and also the linker is unable to find the math library having the pow function.
it is usually resolved if we add -lm at the end of the gcc compile command

**Comment by ChlorinePentoxide** [comment]
@aryashah2k The -lm flag is already included in the gcc compiler flags. Maybe it is something else.
Compilation command:
```shell
$ gcc -w -lm $file > /dev/null
```

**Comment by aryashah2k** [comment]
Alright, if this single file is causing this error, I will try rectifying the code and let you know when you could try compiling it again

**Comment by aryashah2k** [comment]
Error Rectified.
